# Project: Testing
# Makefile created by Dev-C++ 5.4.0

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = testing.o $(RES)
LINKOBJ  = testing.o $(RES)
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include"
BIN      = Testing.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

testing.o: testing.cpp
	$(CPP) -c testing.cpp -o testing.o $(CXXFLAGS)
